import { Snowflake } from "discord.js";
import { CreationOptional, DataTypes, InferAttributes, InferCreationAttributes, Model, Sequelize } from "sequelize";

const sequelize = new Sequelize({
	dialect: 'sqlite',
	storage: "./databases/Category.sqlite",
	logging: false,
	//logging: (...msgs) => console.log(`[Category DATABASE] => ${msgs.forEach(msg => console.log(msg))}`)
})

export interface TournamentCategory extends Model<InferAttributes<TournamentCategory>, InferCreationAttributes<TournamentCategory>> {
	/** Autogenerated id of this category */
	id: CreationOptional<number>,
	/** Guild id of the guild this category belongs to */
	guild_id: Snowflake
	/** Name of this category (length 150) */
	name: string
	/** Description of this category, if any */
	description: CreationOptional<string | null>
}

const CategoryModel = sequelize.define<TournamentCategory>('Category', {
	id: {
		primaryKey: true,
		autoIncrement: true,
		allowNull: false,
		type: DataTypes.INTEGER
	},

	guild_id: {
		type: DataTypes.STRING,
		allowNull: false,
	},

	name: {
		allowNull: false,
		type: DataTypes.STRING({ length: 150 })
	},

	description: {
		allowNull: true,
		type: DataTypes.STRING({ length: 512 })
	}
})

export { CategoryModel }